# /opt/infra/promtail-config.yaml
server:
  http_listen_port: 9080
positions:
  filename: /var/lib/docker/containers/positions.yaml

clients:
  - url: http://loki:3100/loki/api/v1/push

scrape_configs:
  - job_name: docker
    pipeline_stages:
      - docker: {}
    static_configs:
      - targets: [localhost]
        labels:
          job: docker
          __path__: /var/lib/docker/containers/*/*.log
