version: '3.9'
services:
  frontend:
    image: registry.dnp-project.ru/frontend:dev
    restart: unless-stopped
    networks:
      - infra
    labels:
      - "traefik.enable=true"
      - "traefik.http.routers.frontend-stage.rule=Host(`stage.dnp-project.ru`) && PathPrefix(`/`) && !PathPrefix(`/rpc`) && !PathPrefix(`/docs`) && !PathPrefix(`/redoc`)"
      - "traefik.http.routers.frontend-stage.entrypoints=websecure"
      - "traefik.http.routers.frontend-stage.tls=true"
      - "traefik.http.routers.frontend-stage.tls.certresolver=letsencrypt"
      - "traefik.http.routers.frontend-stage.priority=5"

  backend:
    image: registry.dnp-project.ru/backend:dev
    restart: unless-stopped
    networks:
      - infra
    labels:
      - "traefik.enable=true"

      - "traefik.http.services.backend-stage.loadbalancer.server.port=8000"

      - "traefik.http.routers.backend-stage-rpc.rule=Host(`stage.dnp-project.ru`) && (PathPrefix(`/rpc`) || PathPrefix(`/openapi.json`))"
      - "traefik.http.routers.backend-stage-rpc.entrypoints=websecure"
      - "traefik.http.routers.backend-stage-rpc.tls=true"
      - "traefik.http.routers.backend-stage-rpc.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend-stage-rpc.priority=20"
      - "traefik.http.routers.backend-stage-rpc.service=backend-stage"

      - "traefik.http.services.backend-stage-docs.loadbalancer.server.port=8000"
      - "traefik.http.routers.backend-stage-docs.rule=Host(`stage.dnp-project.ru`) && (PathPrefix(`/docs`) || PathPrefix(`/redoc`))"
      - "traefik.http.routers.backend-stage-docs.entrypoints=websecure"
      - "traefik.http.routers.backend-stage-docs.tls=true"
      - "traefik.http.routers.backend-stage-docs.tls.certresolver=letsencrypt"
      - "traefik.http.routers.backend-stage-docs.priority=30"
      - "traefik.http.routers.backend-stage-docs.service=backend-stage-docs"

networks:
  infra:
    external: true
    name: infra_stage
